INHERIT: ./template.yml

site_author: 'Wärmenetz Baudenbach UG'
site_description: 'Homepage der Wärmenetz Baudenbach UG'
site_dir: 'public'
site_name: 'Wärmenetz Baudenbach'
site_url: 'https://www.waermenetz-baudenbach.de'
strict: true

markdown_extensions:
  - zensical.extensions.glightbox:
      auto: true
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg

nav:
  - Startseite: index.md
  - Projekt:
      - Vorbereitung: Projekt/Vorbereitung.md
      - Bauphase: Projekt/Bauphase.md
      - Inbetriebnahme: Projekt/Inbetriebnahme.md
      - Erweiterung: Projekt/Erweiterung.md
      - Kennzahlen: Projekt/Kennzahlen.md
  - Impressum: Impressum.md