INHERIT: ./template.yml

site_author: 'Wärmenetz Baudenbach UG'
site_description: 'Homepage der Wärmenetz Baudenbach UG'
site_dir: 'public'
site_name: 'Wärmenetz Baudenbach'
site_url: 'https://www.waermenetz-baudenbach.de'

plugins:
  - privacy
