INHERIT: ./template.yml

site_author: 'Wärmenetz Baudenbach UG'
site_description: 'Homepage der Wärmenetz Baudenbach UG'
site_dir: 'public'
site_name: 'Wärmenetz Baudenbach'
site_url: 'https://www.waermenetz-baudenbach.de'

markdown_extensions:
  - zensical.extensions.glightbox:
      auto: true
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg

nav:
  - Startseite: index.md
  - Geschichte:
      - Vorbereitung: Geschichte/Vorbereitung.md
      - Bauphase: Geschichte/Bauphase.md
      - Betrieb: Geschichte/Betrieb.md
  - Impressum: Impressum.md